// Generated by Wrangler on Fri May 10 2024 20:11:46 GMT-0700 (Pacific Daylight Time)
// by running `wrangler types`

interface Env {
	ARGO_URL: string;
    ACCESS_CLIENT_ID: string;

    WEBHOOK_SECRET: string;
    ACCESS_CLIENT_SECRET: string;
}
