#:schema node_modules/wrangler/config-schema.json
name = "github-argo-proxy"
main = "src/index.ts"
compatibility_date = "2024-05-02"
compatibility_flags = ["nodejs_compat"]

[placement]
mode = "smart"

[vars]
ARGO_URL = "https://argocd.auth-ing.k3s.brickyard.whitestar.systems/api/webhook"
ACCESS_CLIENT_ID = "37ec1429b56dbbf7c5f7c0e1583f623e.access"
